### ISSUE TITLE
Add install feature for all of the pipeline for rendering

### ISSUE THREAD

**Issue by nstandif** [byu-animation/byu-animation-tools#102]
I don't want a repeat of chasm where I am trying to fix everything on render day.

We need (in no particlular order):
- install shading - check performance of render and warn / reject install if render time way too high.
- install animation - check to see if animation is not at static pose. reject if it is not in static pose or it is somehow not in frame where it is supposed to be.
- install model - check performance of model and check if it is crashing anything. Warn / reject if too slow.
- install lighting - check to see if lighting file is using the most up to date assets and that the otls have not been overridden by the lighters. Reject if there is an override and tell the lighters to use the most up to date definition.

After lighting has been installed, frame-by-frame ifds should be installed. I have more on this later. \

To all of those who I have talked about who are involved in the said pipelines, I'm always watching.

**Comment by bkingery** [comment]
I think this pertains to issue #90

**Comment by eestrada** [comment]
Actually, this **_is_** issue #90, so I am closing it as a duplicate. The current Owned pipeline has no concept of installation, so it is unclear to me what this means in the context of our film.

Trust me, I understand the frustration: I have been the render guy on most films up to Chasm (e.g., Dreamgiver, Butchered Meats, Estefan, etc.). However, all rendering isn't being put off until the last minute on Owned, so we have time to brainstorm, discuss and test various solutions. This is what issue #90 is for.

Under issue #90, explain what you mean by "install". Then we can discuss its merit and how to implement it if we find it to be valuable in our particular lighting/rendering pipeline.
