### ISSUE TITLE
Work on importing alembic into houdini

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#105]
We need a way to do this "automagically"

**Comment by eestrada** [comment]
Are you talking per asset or per scene?

**Comment by bkingery** [comment]
I guess this is more building the assets in Houdini that are going to be animated....

**Comment by eestrada** [comment]
I have some ideas on how we can do this fairly simply for transforms. For deforming geometry, I think we are using bjson sequences.
