### ISSUE TITLE
New Texture tool breaks on environment variables in paths

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#109]
Environment variables such as "$HIP", "$JOB" or "$HOME" in file paths breaks the new texture tool.

**Comment by bkingery** [comment]
Python has a way to expand paths to absolute paths. We should look into
that.

~Transmission sent from my R2 unit.~

**Comment by garretthoyos** [comment]
I'll be in the lab a little later to check it out and finish it up.

On Friday, March 8, 2013, bkingery wrote:

> Python has a way to expand paths to absolute paths. We should look into
> that.
> 
> ~Transmission sent from my R2 unit.~
> On Mar 7, 2013 7:26 PM, "Ethan Estrada" <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>
> wrote:
> 
> > Environment variables such as "$HIP", "$JOB" or "$HOME" in file paths
> > breaks the new texture tool.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/byu-animation/byu-animation-tools/issues/109>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/109#issuecomment-14630243
> .

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by garretthoyos** [comment]
So I'm looking at this while I read about Python. Is it Houdini that doesn't like the file path or Python? It seems like os.path.join and os.path.basename should be relative already. The thing that doesn't work is when a texture is outside of the owned/users/userName path, so even when someone clicks on "Desktop", for example, it breaks. 

I've been reading on forums on how to solve this... The best thing I found was this. 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
fn = os.path.join(os.path.dirname(**file**), 'my_file')

You should be able to get to the parent directory using join(foo, '..'). So from /root/python_files/module/myfile, use os.path.join(os.path.dirname(**file**), '..', '..', 'resources') 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

 I don't know what "foo" means... And can't find an answer. The code right now says os.path.join(x,y) which should make the path relative, but it doesn't allow the user to change directories as far as I see. Any ideas? 

Also, the EXR conversion I found this on the internet: 

import OpenEXR
import Imath
import Image
import array
import sys

def ConvertEXRToJPG(exrfile, jpgfile):
    File = OpenEXR.InputFile(exrfile)
    PixType = Imath.PixelType(Imath.PixelType.FLOAT)
    DW = File.header()['dataWindow']
    Size = (DW.max.x - DW.min.x + 1, DW.max.y - DW.min.y + 1)

```
RedStr = File.channel('R', PixType)
GreenStr = File.channel('G', PixType)
BlueStr = File.channel('B', PixType)

Red = array.array('f', RedStr)
Green = array.array('f', GreenStr)
Blue = array.array('f', BlueStr)

for I in range(len(Red)):
    Red[I] = EncodeToSRGB(Red[I])

for I in range(len(Green)):
    Green[I] = EncodeToSRGB(Green[I])

for I in range(len(Blue)):
    Blue[I] = EncodeToSRGB(Blue[I])

rgbf = [Image.fromstring("F", Size, Red.tostring())]
rgbf.append(Image.fromstring("F", Size, Green.tostring()))
rgbf.append(Image.fromstring("F", Size, Blue.tostring()))

rgb8 = [im.convert("L") for im in rgbf]
Image.merge("RGB", rgb8).save(jpgfile, "JPEG", quality=95)
```

def EncodeToSRGB(v):
    if (v <= 0.0031308):
        return (v \* 12.92) \* 255.0
    else:
        return (1.055_(v_*(1.0/2.4))-0.055) \* 255.0

**Comment by eestrada** [comment]
I'll be in in a few minutes and we can talk about file conversion. :)
