### ISSUE TITLE
Maya discard doesn't unlock the asset.

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#132]

**Comment by jmoborn** [comment]
I've been testing discard out and I can't get it to break. Does anyone know who has had trouble with it and what they were doing? That might help me find the bug

**Comment by bkingery** [comment]
I don't know Jeremy... I had the same question because I haven't gotten it to break either.  Someone brought it up yesterday again though so I figured I would make the issue so we can try to figure out what people are doing.

My guess at this point is either a user error, or a file permissions issue.
