### ISSUE TITLE
Optimize check-in routines for animation and layout

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#137]
Currently, check in for animation and layout exports alembic files (along with doing some other stuff). We could possibly fork a subprocess to put this work in another thread. Or we could run a nightly script to convert files. Or (my least favorite) we could create a separate tool to export animation to Alembic :P .

**Comment by bkingery** [comment]
For now it pops up with a dialog asking if they want to export alembic.  This way the only have to wait when a change in final.

**Comment by eestrada** [comment]
Sounds good. This may be good enough to just be the final solution. Let's see how things progress as the animators use this.
