### ISSUE TITLE
Lighting scene checkin will occasionally bring up exception trace

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#166]
It complains that it can't open a directory as a file. I don't know whey it is even trying to do that to start with.

**Comment by bkingery** [comment]
I'm assuming that Houdini is creating a backup folder and then our code is trying to open that as the file.

**Comment by bkingery** [comment]
#185 Should have taken care of this.
We may still need to go and delete the old backup folders as needed
