### ISSUE TITLE
Create "Delete Asset" tool in Houdini

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#36]
Make tons and tons of warnings!!!

**Comment by garretthoyos** [comment]
I'll do this

**Comment by bkingery** [comment]
We may want this to be password protected.

**Comment by eestrada** [comment]
FYI, the password protection will eliminate the need for the pop ups warnings.

**Comment by bkingery** [comment]
Ethan created this.  There are a couple tweeks that would be nice, so I think it would good if you to implement. 
I hope you didn't get too far on it.

**Comment by garretthoyos** [comment]
guess i was too slow...

On Sat, Feb 16, 2013 at 7:44 PM, bkingery notifications@github.com wrote:

> Ethan created this. There are a couple tweeks that would be nice, so I
> think it would good if you to implement.
> I hope you didn't get too far on it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/36#issuecomment-13679701.

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by eestrada** [comment]
I am sorry. I didn't mean to make you feel bad. I was just trying to get my mind off some stuff and working on this happened to fit the bill. I won't poach your assignments from now on. I promise. Let me know if you need any help on your next GT assignment.

**Comment by nstandif** [comment]
Is this finished? Can we close this issue?

**Comment by bkingery** [comment]
Do not use this tool until issue #81 is fixed.
