### ISSUE TITLE
Maya holds on to previous scene name after checkin

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#37]
1. checkout asset
2. checkin asset
3. query scene name

It might be a history issue.

**Comment by bkingery** [comment]
Remove | (pipes) from names.
Delete history

**Comment by bkingery** [comment]
I replaced the "|" with "_" in the obj names.

**Comment by ghost** [comment]
Has this been fixed Brian? Or is work still needed?

**Comment by bkingery** [comment]
We still need to delete the history on checkin.  So its only partially done.

**Comment by bkingery** [comment]
People have not reported problems after I changed "|" to "_" so I'm closing this issue.  I think that was the problem, not the history.
