### ISSUE TITLE
Add Inspirational quotes to "brent" button in maya

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#39]
This would be good to for someone to get a feel for how the shelf is set up.
Also, this would be a good opportunity for someone to learn python.

**Comment by eestrada** [comment]
The idea has been suggested a few times by a few different people to have the quotes read from a plain text file delimited by something like newlines so that adding or removing quotes is separate from the code itself.

**Comment by mrmurphy** [comment]
That'd be fun
We could even set up a little web interface with bottle.py so it's easy to add to. :cake: ! :camel: !

**Comment by bkingery** [comment]
Its all in place.  To add quotes simply add a line to the brent_quotes.txt file.

**Comment by mrmurphy** [comment]
That's awesome!

**Comment by eestrada** [comment]
Huzzah. I am going to add some now! Hopefully that will make having to sit
at home less dreadfully dull. :)

On Fri, Mar 1, 2013 at 1:45 PM, Murphy Randle notifications@github.comwrote:

> That's awesome!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/39#issuecomment-14310387
> .

## 

Ethan Estrada

"Education is a progressive discovery of our own ignorance." - Will Durant

**Comment by mrmurphy** [comment]
Why are you sitting at home? Did you break yourself?

## 

Murphy Randle
Git Enthusiast, Python Slinger, & Ruby Gumshoe
http://www.MurphyRandle.com

**Comment by eestrada** [comment]
Yes, sick with Bronchitis.

On Fri, Mar 1, 2013 at 5:08 PM, Murphy Randle notifications@github.comwrote:

> Why are you sitting at home? Did you break yourself?
> 
> ## 
> 
> Murphy Randle
> Git Enthusiast, Python Slinger, & Ruby Gumshoe
> http://www.MurphyRandle.com
> 
> On Friday, March 1, 2013 at 2:56 PM, Ethan Estrada wrote:
> 
> > Huzzah. I am going to add some now! Hopefully that will make having to
> > sit
> > at home less dreadfully dull. :)
> > 
> > On Fri, Mar 1, 2013 at 1:45 PM, Murphy Randle <notifications@github.com(mailto:
> > notifications@github.com)>wrote:
> > 
> > > That's awesome!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/byu-animation/byu-animation-tools/issues/39#issuecomment-14310387>
> > > 
> > > .
> > 
> > ## 
> > 
> > Ethan Estrada
> > 
> > "Education is a progressive discovery of our own ignorance." - Will
> > Durant
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/byu-animation/byu-animation-tools/issues/39#issuecomment-14313751).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/39#issuecomment-14318642
> .

## 

Ethan Estrada

"Education is a progressive discovery of our own ignorance." - Will Durant
