### ISSUE TITLE
Update "New" tool in Houdini

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#4]
Tool needs to be fixed so that new geometry is created in the current context instead of in /obj every time (which is the current way it is being done).

**Comment by bkingery** [comment]
I tried to create a new container and it said 'containerTemplate' doesn't exists.  It looks like its having a problem finding our custom otls.

**Comment by eestrada** [comment]
Oh yeah, I forgot: for my testing I manually moved them to $JOB/PRODUCTION/otls. We should probably modify project_env.sh to copy them over when the directory structure is created. Normally they live under "otl_templates". I feel dumb for not thinking of that.

![doh](https://f.cloud.github.com/assets/1664385/105763/14b06486-69c6-11e2-89f9-8a01c99676ad.jpg)
