### ISSUE TITLE
Set up default Houdini pre-sets and preferences

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#41]
Such as... 

hq_render pre-sets
mantra pre-sets
linear workflow 
geo node pre-sets

...etc...

**Comment by eestrada** [comment]
This is mostly done. There still aren't presets for the builtin geo node, only for the geometry template node that we created (this is really what people should be using anyway).

**Comment by ghost** [comment]
Thanks Ethan. Are the presets for the builtin node something we would like to have done or just push off to the side?

**Comment by eestrada** [comment]
We can get it done it. It shouldn't take more than 10 minutes today. :)
