### ISSUE TITLE
Get common names along with CS account names

### ISSUE THREAD

**Issue by nstandif** [byu-animation/byu-animation-tools#54]
User ids are often cryptic, but common names(cn) typically are not. If I do ldapsearch -LLL "uid=CSUSERID" cn on of the cs lab machines, I can find the name of the person associated with CSUSERID. I want to add this feature to our shelf tools so that we have the person's common name instead of their user id.

**Comment by bkingery** [comment]
Lets display both the full name and the username

**Comment by eestrada** [comment]
It may be easiest to simply ask the user their name the first time they use the pipeline (at the same time their user folder is made). Then we just save their name in a hidden file inside their user folder. Or we check to see if the hidden file exists, and if it doesn't, run the pop up. It is a hacky solution, but seems faster/easier than integrating LDAP. At least in my mind.

**Comment by nstandif** [comment]
We'd just run ldaplookup as a subprocess and parse the output in python.
It's not too much more difficult than making a pop up.

**Comment by eestrada** [comment]
Cool. If it isn't much hassle I am fine with it. I have tried some of the ldap command line tools on these machines and I am not getting a great result; lots of notifications about authentication. However, I am probably using the tools wrong. Does python have any built-in stuff for talking with LDAP?

**Comment by eestrada** [comment]
Never mind, I actually read the command you ran and used it and you are right, it is a simple command with easy to parse output. I think it might be good to cache the results in a database or something, so we only need to run that code if the person by that user name does not already exist in the database.

**Comment by bkingery** [comment]
Managing our own database for names is probably over kill.  An LDAP query can be one line of code.

**Comment by eestrada** [comment]
Truthiness.

**Comment by eestrada** [comment]
This has been implemented for Maya as well now in issue #115. Thus, I am closing this issue.
