### ISSUE TITLE
Create Unlock Asset Tool for maya

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#56]
This will unlock the asset so others can check it out.
We need to decide what we want to do with the file that was checked out.
We may consider making this one password protected.

**Comment by nstandif** [comment]
Let's move the file to a hidden folder like .trash. This way, the file can still be recovered and it doesn't wreck it if it is attempted to be checked out again.

**Comment by eestrada** [comment]
Lots of people seem to have this problem with Maya assets. Either the checkin/discard tools are slightly borked, or (more likely) people are just being lazy and checking stuff out without ever checking it back in. Either way, I am bumping this up high priority. We are moving out of the modelling phase and so it ought to be less of an issue. Still, I don't want to have to track people down or modify '.nodeInfo' files by hand any more just to make sure folks can move forward with their work.

**Comment by bkingery** [comment]
Melissa is working on this.

**Comment by eestrada** [comment]
Excellent...

It is now officially assigned to her.

**Comment by bkingery** [comment]
The tool is there.  Use at your own risk.
