### ISSUE TITLE
Disallow checking in/out geometryTemplate nodes

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#62]
This has already been a problem a number of times (users overwriting default values for the geometryTemplate asset). Thus, there will be three code paths for checkin/checkout:

```
 1. Container asset (this is done)
 2. geometryTemplate asset (not yet implemented)
 3. All other asset types (not sure what is going on with this now)
```

**Comment by eestrada** [comment]
FIXED! BOO-YA!

**Comment by bkingery** [comment]
Nice you rock!
