### ISSUE TITLE
Modify Houdini Checkin/Checkout to accomidate houdini files.

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#71]
Same sort of thing with as with maya.
If a node is not selected assume they want to checkout/checkin a .hip scene

However, with checkin we should prompt for confirmation because it would be easy to accidentally forget to select a node.

**Comment by eestrada** [comment]
The deadline for getting this working is the lighting start date. Actually, it may be before that when we start video game animation in Houdini (if this isn't done using HDAs).

**Comment by bkingery** [comment]
Yes we need to get on this. I'm coming in to code today so if nobody jumps
on it hopefully I can get it done. It shouldn't be to bad.

~Transmission sent from my R2 unit.~

**Comment by bkingery** [comment]
done.
