### ISSUE TITLE
Alembic tagger throws error

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#77]
When testing the Alembic tagger on a random piece of geometry, the tool throws the following error in the script editor:

`# Error: AttributeError: 'parent' is not a Qt property or a signal #`

**Comment by eestrada** [comment]
I don't know the Alembic tagger code well enough to understand what is causing this. I may just be using the tool incorrectly.

**Comment by mrmurphy** [comment]
Ah, good catch. I'll look deeper into this.
