### ISSUE TITLE
Assets within other assets do not update properly

### ISSUE THREAD

**Issue by eestrada** [byu-animation/byu-animation-tools#79]
For instance, in the Abby Family room, if the lamp asset is updated (in Houdini, not Maya), the Abby family room asset will still have the old version of the asset's interior nodes. Dropping a new copy of the lamp has the new settings and nodes, but a version already laid down stays the same. We should probably create a tool to "refresh" an asset on demand. This ought to keep the old behaviour (which is a good thing under a lot of circumstances), but also allow people to update to the latest version of the asset as needed.

**Comment by bkingery** [comment]
This is connected to Issue #81

**Comment by bkingery** [comment]
Create a tool to refresh the selected otls.

A potential solution could be.
right click -> change type -> 
 *make sure "Keep Name" and "Keep Parameters" are selected
 *change to template node
Accept

right click -> change type -> change back to operator type.

**Comment by nstandif** [comment]
Changing the type in python doesn't do the same thing, unless there is something I am missing.

here is what I am doing with a single node

``` python
# select the child node
child = hou.selectedNodes()[-1].children()[-1]

# save the child's type name
child_type = child.type().name()

# change the child's type
child.changeNodeType("geometryTemplate")

# select the child again
child = hou.selectedNodes()[-1].children()[-1]

# change the node type back
child.changeNodeType(child_type)
```

**Comment by bkingery** [comment]
I don't think you want to change the children.  You want to change the top
level node.

On Wed, Feb 27, 2013 at 5:19 PM, nstandif notifications@github.com wrote:

> Changing the type in python doesn't do the same thing, unless there is
> something I am missing.
> 
> here is what I am doing with a single node
> 
> # select the child nodechild = hou.selectedNodes()[-1].children()[-1]
> 
> # save the child's type namechild_type = child.type().name()
> 
> # change the child's typechild.changeNodeType("geometryTemplate")
> 
> # select the child againchild = hou.selectedNodes()[-1].children()[-1]
> 
> # change the node type backchild.changeNodeType(child_type)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/79#issuecomment-14209111
> .

## 

Brian Kingery
BYU - OIT Core Services
Desk: 801-422-5811
Location: ITB 2226L

**Comment by bkingery** [comment]
I don't know how far you have gotten with this, but I'm going to implement it right now.  (unless you are done)
