### ISSUE TITLE
Create New and Update Texture Shelf tools in houdini

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#83]
New will ask them which asset the texture is for, and which file they want to use.
It will then convert their file to an .exr and remove the gamma and the place it in the assets 'images' folder with a proper naming convention.

Update will ask which asset then which texture, and which file they want to use.
It will then convert their file to an .exr and remove the gamma and REPLACE the selected texture file in the assets 'images' folder.

**Comment by garretthoyos** [comment]
K can I pretty please have this one?

**Comment by bkingery** [comment]
Sure thing.  This one is going to be kind of a larger assignment but I can help you with it. 
We will need it by the time shading starts.  Whenever that is. 
I've already started some stuff for it, so I give you the details tomorrow or something.

**Comment by garretthoyos** [comment]
Okay, I just really think I want to put this in my portfolio. If you want
to assign a part of this to me thats fine too but I really like the idea of
learning this since it's right up my alley.

On Thu, Feb 21, 2013 at 7:54 PM, bkingery notifications@github.com wrote:

> Sure thing. This one is going to be kind of a larger assignment but I can
> help you with it.
> We will need it by the time shading starts. Whenever that is.
> I've already started some stuff for it, so I give you the details tomorrow
> or something.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/83#issuecomment-13925990.

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by bkingery** [comment]
Yep sure thing.  Let's make sure to talk it through tomorrow. It will be good for you to being doing this one too because we want it to be intuitive for the texture artists.

**Comment by eestrada** [comment]
Hi Garret. I was the one who asked for these tools for the shading team, so blame me if the initial work flow is a pain. Here are the command line utilities that I want to have run on the input images (I don't think there is anything natively in Python to easily do image manipulation work):

```
# Comments start with hash (i.e. pound) symbol
# Widen the data type to 16 bits so that fixing gamma doesn't lose significant data
iconvert -d 16 input_file.image_extension working_file.png

# Fix gamma in working file
icomposite working_file.png = gamma 0.45454545454545 working_file.png

# Convert to exr with final settings for tiled storage and ZIP compression
iconvert -d half working_file.png final_file.exr storage tile tilex 64 tiley 64 compression zip
```

FYI, iconvert and icomposite are command-line utilities that ship with Houdini. If we find other utilities that better fit our needs, we will swap these out for those.

Like Brian, I am happy to help so don't be afraid to ask.

To my knowledge, the shading team's official start date is within the next few weeks.

**Comment by garretthoyos** [comment]
So I really like this assignment and I really wanna figure it out so that I
can say "hey look what i did!! (to all the studios)".  To you it might not
be a big deal because you do this thing all the time, but for me it's like
being a pre-major getting the go ahead to model the first thing on a senior
film. Haha, so thats kind of how I feel. I'm stoked to do this but I'll
need guidance along the way when I (figuratively) put in 30 edgeloops when
you need 2. Thanks for the offer of help. Right now so far I have this .ui
created in Qt Designer.

:)

On Fri, Feb 22, 2013 at 10:24 PM, Ethan Estrada notifications@github.comwrote:

> Hi Garret. I was the one who asked for these tools for the shading team,
> so blame me if the initial work flow is a pain. Here are the command line
> utilities that I want to have run on the input images (I don't think there
> is anything natively in Python to easily do image manipulation work):
> 
> # Comments start with hash (i.e. pound) symbol
> 
> # Widen the data type to 16 bits so that fixing gamma doesn't lose significant data
> 
> iconvert -d 16 input_file.image_extension working_file.png
> 
> # Fix gamma in working file
> 
> icomposite working_file.png = gamma 0.45454545454545 working_file.png
> 
> # Convert to exr with final settings for tiled storage and ZIP compression
> 
> iconvert -d half working_file.png final_file.exr storage tile tilex 64 tiley 64 compression zip
> 
> FYI, iconvert and icomposite are command-line utilities that ship with
> Houdini. If we find other utilities that better fit our needs, we will swap
> these out for those.
> 
> Like Brian, I am happy to help so don't be afraid to ask.
> 
> To my knowledge, the shading team's official start date is within the next
> few weeks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/83#issuecomment-13985559.

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by eestrada** [comment]
IMHO, you probably don't need Qt Designer; it is currently a bit overkill for the UI needs of the tool. I worry about you getting stuck on the Qt stuff and not being able to get around to the real meat of the code (e.g. format conversion, getting the list of assets, placing the texture in the correct place, etc.). The tool only really needs a file chooser and a list of assets to choose from and both these types of windows are available in the native Houdini python API. Some example code can be found in [hou_asset_mgr.py](https://github.com/byu-animation/byu-animation-tools/blob/master/houdini-tools/python2.6libs/hou_asset_mgr.py) under the `def newGeo(hpath):` method. If you want to re-factor the UI code later using Qt, that is fine (and fairly straightforward). However, my suggestion for now is to use the (much) simpler Houdini UI tools until the tool is working.

What do you think Brian? Agree? Disagree? Enjoy spicy Indian food?

**Comment by bkingery** [comment]
I love spicy Indian food!

Garrett pretty much has the Ui already built, and it's looking sweet. We
pretty much already have all of the other code except for file conversion.
So I don't think it's that big of a deal.  Also, this way it can be
reusable as a stand alone tool as it really has nothing to with Houdini.

Ultimately I think it's whatever Garrett wants to do with it.

~Transmission sent from my R2 unit.~

**Comment by bkingery** [comment]
The shading deadline has been pushed up, so we need this very soon.  I would like to say by the end of the week we at least need the file copy stuff in place.  It would be nice to have the file conversion in place as well.

What do you think?

**Comment by eestrada** [comment]
If you(Brian) or I sit down with Garret on Saturday, i think he can have
the backend functionality done within a few hows. I can't say for the GUI
frontend stuff since i haven't coded with Qt before.

-Ethan

**Comment by garretthoyos** [comment]
Okay lets do it. Thursday Friday and Saturday for sure I can dedicate
several hours to finishing this. If I need to change to do the Houdini
interface instead I'll do it if it's faster and easier.

On Tue, Feb 26, 2013 at 4:38 PM, Ethan Estrada notifications@github.comwrote:

> If you(Brian) or I sit down with Garret on Saturday, i think he can have
> the backend functionality done within a few hows. I can't say for the GUI
> frontend stuff since i haven't coded with Qt before.
> 
> -Ethan
> On Feb 26, 2013 3:37 PM, "bkingery" notifications@github.com wrote:
> 
> > The shading deadline has been pushed up, so we need this very soon. I
> > would like to say by the end of the week we at least need the file copy
> > stuff in place. It would be nice to have the file conversion in place as
> > well.
> > 
> > What do you think?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/byu-animation/byu-animation-tools/issues/83#issuecomment-14144433>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/83#issuecomment-14147148
> .

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by bkingery** [comment]
It might be easier to use the houdini modules. But that all depends on how far you have gotten with the UI design.  Converting the .ui file to python takes literally like 2 seconds with the following command

pyuic4 texture_checkin.ui > texture_checkin.py

So its up to you and how much time you want to spend/have spent on the UI design.

**Comment by garretthoyos** [comment]
I think the UI design is the easiest part... I mean, isn't it just clicking
and dragging things to make it visually easy for whoever sees it? If you're
referring to any coding, I have done none.

On Tue, Feb 26, 2013 at 4:46 PM, bkingery notifications@github.com wrote:

> It might be easier to use the houdini modules. But that all depends on how
> far you have gotten with the UI design. Converting the .ui file to python
> takes literally like 2 seconds with the following command
> 
> pyuic4 texture_checkin.ui > texture_checkin.py
> 
> So its up to you and how much time you want to spend/have spent on the UI
> design.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-animation/byu-animation-tools/issues/83#issuecomment-14147466
> .

## 

*
Garrett Hoyos
BYU Animation
Shading/Texturing Artist
785.608.9356*

**Comment by bkingery** [comment]
I'll I'm referring to is the clicking and dragging.  If that is done, then lets use it.  We will link the code to your UI instead of the houdini stuff.

**Comment by eestrada** [comment]
This is on a related but separate note. I think i figured out how we can
abstract Qt dialogs. We can have a function in the "ui_tools" module that
is called something like "QtDialog". It's input would be a QtDialog object.
The function would bind it to whatever software it was running in (Houdini,
Maya, Nuke etc.) and then return a tuple of the harvested values. I think
it is a good generalization to abstract the underlying issues of how the
window is bound to the underlying software while still allowing all the
flexibility that Qt affords us. Of course, this is with my somewhat limited
understanding of the return values from Qt UI components.

If this is the way we decide to go, then we need to have this in place
before Garret gets too deep into the UI Python coding aspect of the work.

**Comment by bkingery** [comment]
Garrett has finished this.
