### ISSUE TITLE
Group Permissions of files are read only

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#92]
I believe this is why people are having problems checking things in.

I will talk to the CSRs.

**Comment by bkingery** [comment]
I spoke with the CSRs.  They are fixing this for us.

**Comment by eestrada** [comment]
I thought this was changed before and the fact that it isn't or it has reverted to the old behaviour has me somewhat worried. It may be a good idea to forcefully set file permissions whenever we do anything regarding files (moving, replacing, etc.).

**Comment by ghost** [comment]
Did the CRS get this fixed for us Ethan or Brian?

**Comment by eestrada** [comment]
We haven't had any problems recently, so I assume so.

**Comment by bkingery** [comment]
I asked again 2 days ago and the still had not done it.  I don't know where
we stand right now.

~Transmission sent from my R2 unit.~
