### ISSUE TITLE
Alembic Converter Error

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#97]
When I run the converter it spews this output

Warning: file: /usr/autodesk/maya/scripts/startup/initialStartup.mel line 187: Y-axis is already the Up-axis
/groups/owned/PRODUCTION/shots/test02/animation/src/v7/test02_animation.mb
/groups/owned/PRODUCTION/shots/test02/animation_cache/abc/test02_animation.abc
File read in 0 seconds.
AbcExport v1.0 using Alembic 1.0.0 (built Aug 10 2011 13:27:16)
AbcExport -j " -frameRange -4.0 29.0 -step 0.25 -writeVisibility -file /groups/owned/PRODUCTION/shots/test02/animation_cache/abc/test02_animation.abc"
**\* glibc detected **\* /opt/hfs.current/python/bin/python2.6-bin: free(): invalid pointer: 0x00000000020f0f98 ***
======= Backtrace: =========
/lib64/libc.so.6[0x31c1475916]
/usr/lib64/tls/libnvidia-tls.so.310.19[0x3a9a801cd1]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:03 5865583                            /opt/hfs12.1.125/python/bin/python2.6-bin
00600000-00601000 r--p 00000000 08:03 5865583                            /opt/hfs12.1.125/python/bin/python2.6-bin
00601000-00602000 rw-p 00001000 08:03 5865583                            /opt/hfs12.1.125/python/bin/python2.6-bin
020d8000-09022000 rw-p 00000000 00:00 0                                  [heap]
31c0c00000-31c0c0e000 r-xp 00000000 08:03 32852                          /lib64/ld-2.12.so
31c0c0e000-31c0c0f000 r-xp 0000e000 08:03 32852                          /lib64/ld-2.12.so
31c0c0f000-31c0c20000 r-xp 0000f000 08:03 32852                          /lib64/ld-2.12.so
31c0e1f000-31c0e20000 r--p 0001f000 08:03 32852                          /lib64/ld-2.12.so
31c0e20000-31c0e21000 rw-p 00020000 08:03 32852                          /lib64/ld-2.12.so
31c0e21000-31c0e22000 rw-p 00000000 00:00 0 
31c1000000-31c1002000 r-xp 00000000 08:03 49256                          /lib64/libdl-2.12.so
31c1002000-31c1202000 ---p 00002000 08:03 49256                          /lib64/libdl-2.12.so
31c1202000-31c1203000 r--p 00002000 08:03 49256                          /lib64/libdl-2.12.so
31c1203000-31c1204000 rw-p 00003000 08:03 49256                          /lib64/libdl-2.12.so
31c1400000-31c1589000 r-xp 00000000 08:03 32853                          /lib64/libc-2.12.so
31c1589000-31c1789000 ---p 00189000 08:03 32853                          /lib64/libc-2.12.so
31c1789000-31c178d000 r--p 00189000 08:03 32853                          /lib64/libc-2.12.so
31c178d000-31c178e000 rw-p 0018d000 08:03 32853                          /lib64/libc-2.12.so
31c178e000-31c1793000 rw-p 00000000 00:00 0 
31c1800000-31c1817000 r-xp 00000000 08:03 32867                          /lib64/libpthread-2.12.so
31c1817000-31c1a17000 ---p 00017000 08:03 32867                          /lib64/libpthread-2.12.so
31c1a17000-31c1a18000 r--p 00017000 08:03 32867                          /lib64/libpthread-2.12.so
31c1a18000-31c1a19000 rw-p 00018000 08:03 32867                          /lib64/libpthread-2.12.so
31c1a19000-31c1a1d000 rw-p 00000000 00:00 0 
31c1c00000-31c1c83000 r-xp 00000000 08:03 32859                          /lib64/libm-2.12.so
31c1c83000-31c1e82000 ---p 00083000 08:03 32859                          /lib64/libm-2.12.so
31c1e82000-31c1e83000 r--p 00082000 08:03 32859                          /lib64/libm-2.12.so
31c1e83000-31c1e84000 rw-p 00083000 08:03 32859                          /lib64/libm-2.12.so
31c2000000-31c2007000 r-xp 00000000 08:03 32869                          /lib64/librt-2.12.so
31c2007000-31c2206000 ---p 00007000 08:03 32869                          /lib64/librt-2.12.so
31c2206000-31c2207000 r--p 00006000 08:03 32869                          /lib64/librt-2.12.so
31c2207000-31c2208000 rw-p 00007000 08:03 32869                          /lib64/librt-2.12.so
31c2400000-31c24e4000 r-xp 00000000 08:03 49250                          /lib64/libglib-2.0.so.0.2200.5
31c24e4000-31c26e3000 ---p 000e4000 08:03 49250                          /lib64/libglib-2.0.so.0.2200.5
31c26e3000-31c26e5000 rw-p 000e3000 08:03 49250                          /lib64/libglib-2.0.so.0.2200.5
31c2c00000-31c2c1d000 r-xp 00000000 08:03 32897                          /lib64/libselinux.so.1
31c2c1d000-31c2e1c000 ---p 0001d000 08:03 32897                          /lib64/libselinux.so.1
31c2e1c000-31c2e1d000 r--p 0001c000 08:03 32897                          /lib64/libselinux.so.1
31c2e1d000-31c2e1e000 rw-p 0001d000 08:03 32897                          /lib64/libselinux.so.1
31c2e1e000-31c2e1f000 rw-p 00000000 00:00 0 
31c3400000-31c3416000 r-xp 00000000 08:03 49229                          /lib64/libresolv-2.12.so
31c3416000-31c3616000 ---p 00016000 08:03 49229                          /lib64/libresolv-2.12.so
31c3616000-31c3617000 r--p 00016000 08:03 49229                          /lib64/libresolv-2.12.so
31c3617000-31c3618000 rw-p 00017000 08:03 49229                          /lib64/libresolv-2.12.so
31c3618000-31c361a000 rw-p 00000000 00:00 0 
31c3800000-31c3843000 r-xp 00000000 08:03 32900                          /lib64/libgobject-2.0.so.0.2200.5
31c3843000-31c3a43000 ---p 00043000 08:03 32900                          /lib64/libgobject-2.0.so.0.2200.5
31c3a43000-31c3a45000 rw-p 00043000 08:03 32900                          /lib64/libgobject-2.0.so.0.2200.5
31c4000000-31c4004000 r-xp 00000000 08:03 49267                          /lib64/libgthread-2.0.so.0.2200.5
31c4004000-31c4203000 ---p 00004000 08:03 49267                          /lib64/libgthread-2.0.so.0.2200.5
31c4203000-31c4204000 rw-p 00003000 08:03 49267                          /lib64/libgthread-2.0.so.0.2200.5
31c4800000-31c481b000 r-xp 00000000 08:03 655425                         /usr/lib64/libxcb.so.1.1.0
31c481b000-31c4a1a000 ---p 0001b000 08:03 655425                         /usr/lib64/libxcb.so.1.1.0
31c4a1a000-31c4a1b000 rw-p 0001a000 08:03 655425                         /usr/lib64/libxcb.so.1.1.0
31c4c00000-31c4c02000 r-xp 00000000 08:03 524373                         /usr/lib64/libXau.so.6.0.0
31c4c02000-31c4e02000 ---p 00002000 08:03 524373                         /usr/lib64/libXau.so.6.0.0
31c4e02000-31c4e03000 rw-p 00002000 08:03 524373                         /usr/lib64/libXau.so.6.0.0
31c5000000-31c5139000 r-xp 00000000 08:03 622680                         /usr/lib64/libX11.so.6.3.0
31c5139000-31c5339000 ---p 00139000 08:03 622680                         /usr/lib64/libX11.so.6.3.0
31c5339000-31c533f000 rw-p 00139000 08:03 622680                         /usr/lib64/libX11.so.6.3.0
31c5400000-31c5425000 r-xp 00000000 08:03 655371                         /usr/lib64/libpng12.so.0.49.0
31c5425000-31c5625000 ---p 00025000 08:03 655371                         /usr/lib64/libpng12.so.0.49.0
31c5625000-31c5626000 rw-p 00025000 08:03 655371                         /usr/lib64/libpng12.so.0.49.0
31c5800000-31c5811000 r-xp 00000000 08:03 639055                         /usr/lib64/libXext.so.6.4.0
maya encountered a fatal error

Signal: 6 (Unknown Signal)
Fatal Error. Attempting to save in /usr/tmp/bkingery.20130301.1238.ma

**Comment by mrmurphy** [comment]
Oh my goodness. That's frustrating beyond belief. Thanks for the descriptive errors, Maya.

Try removing this flag from the ABC command maybe?
`-writeVisibility`

**Comment by bkingery** [comment]
needed to add os._exit(0) to the script, cuz maya is stupid.
